import { z } from "zod";

// ---------------------------------------------------------------------------
// AI Response Schemas — validate structured output from LLM providers
// ---------------------------------------------------------------------------

/**
 * Schema for the AI-generated stack explanation.
 * Used to validate LLM output when explaining why a stack was recommended.
 */
export const AiExplanationResponseSchema = z.object({
  summary: z
    .string()
    .describe("A 2-3 sentence summary of why this stack was chosen."),
  keyReasons: z
    .array(z.string())
    .min(1)
    .max(5)
    .describe("Top reasons this stack is recommended for the given idea."),
  confidence: z
    .number()
    .min(0)
    .max(1)
    .describe("Confidence score from 0 to 1 for this recommendation."),
});

export type AiExplanationResponse = z.infer<typeof AiExplanationResponseSchema>;

/**
 * Schema for the AI-generated tradeoff analysis.
 */
export const AiTradeoffResponseSchema = z.object({
  tradeoffs: z
    .array(
      z.object({
        aspect: z.string().describe("The area of concern (e.g., 'Performance', 'Cost', 'DX')."),
        description: z.string().describe("What the tradeoff actually means."),
        severity: z.enum(["low", "medium", "high"]).describe("How significant this tradeoff is."),
      }),
    )
    .min(1)
    .max(8),
});

export type AiTradeoffResponse = z.infer<typeof AiTradeoffResponseSchema>;

/**
 * Schema for the "why not" explanation for rejected alternatives.
 */
export const AiWhyNotResponseSchema = z.object({
  reason: z.string().describe("Why this alternative stack was not chosen as the primary."),
  betterFor: z
    .string()
    .optional()
    .describe("Scenarios where this alternative would actually be better."),
});

export type AiWhyNotResponse = z.infer<typeof AiWhyNotResponseSchema>;

/**
 * Schema for implementation roadmap generated by AI.
 */
export const AiRoadmapResponseSchema = z.object({
  phases: z
    .array(
      z.object({
        name: z.string().describe("Phase name (e.g., 'Foundation', 'Core Features')."),
        duration: z.string().describe("Estimated duration (e.g., '1-2 weeks')."),
        tasks: z
          .array(z.string())
          .min(1)
          .max(6)
          .describe("Key tasks in this phase."),
      }),
    )
    .min(2)
    .max(5),
  totalEstimate: z
    .string()
    .describe("Total estimated timeline (e.g., '6-8 weeks')."),
});

export type AiRoadmapResponse = z.infer<typeof AiRoadmapResponseSchema>;
