/**
 * README.md generator
 * Creates comprehensive setup guide with all sections
 */

import type { Tool, Diagnostic } from '@/types';

/**
 * Generate README.md content
 */
export function generateReadme(config: {
  title?: string;
  intro?: string;
  tools: Tool[];
  postInstallSteps: string[];
  envVars: Record<string, string>;
  docsLinks: string[];
  diagnostics: Diagnostic[];
  includeCaveats?: boolean;
}): string {
  const lines: string[] = [];
  
  // Title
  lines.push(`# ${config.title || 'StackFast Application'}`);
  lines.push('');
  
  // Overview
  lines.push('## Overview');
  lines.push('');
  if (config.intro) {
    lines.push(config.intro);
  } else {
    lines.push('A modern full-stack application built with:');
    lines.push('');
    config.tools.forEach(tool => {
      lines.push(`- **${tool.name}**: ${tool.description}`);
    });
  }
  lines.push('');
  
  // Prerequisites
  lines.push('## Prerequisites');
  lines.push('');
  lines.push('Before you begin, ensure you have the following installed:');
  lines.push('');
  lines.push('- Node.js (v18 or higher)');
  lines.push('- npm or yarn');
  
  // Check if database is needed
  const hasDatabase = config.tools.some(t => t.categoryId === 'database');
  if (hasDatabase) {
    const dbTool = config.tools.find(t => t.categoryId === 'database');
    if (dbTool) {
      lines.push(`- ${dbTool.name} (for database)`);
    }
  }
  lines.push('');
  
  // Installation & Commands
  lines.push('## Installation & Commands');
  lines.push('');
  lines.push('Follow these steps in order:');
  lines.push('');
  
  config.postInstallSteps.forEach((step, index) => {
    lines.push(`${index + 1}. \`${step}\``);
  });
  lines.push('');
  
  // Environment Variables
  if (Object.keys(config.envVars).length > 0) {
    lines.push('## Environment Variables');
    lines.push('');
    lines.push('Copy `.env.example` to `.env.local` and fill in the following variables:');
    lines.push('');
    
    for (const [key, value] of Object.entries(config.envVars)) {
      lines.push(`- \`${key}\`: ${getEnvVarDescription(key, value)}`);
    }
    lines.push('');
  }
  
  // Caveats (warnings from diagnostics)
  if (config.includeCaveats) {
    const warnings = config.diagnostics.filter(d => d.level === 'warning');
    if (warnings.length > 0) {
      lines.push('## Caveats');
      lines.push('');
      lines.push('Please note the following:');
      lines.push('');
      
      warnings.forEach(warning => {
        lines.push(`- **${warning.message}**`);
      });
      lines.push('');
    }
  }
  
  // Links to Documentation
  if (config.docsLinks.length > 0) {
    lines.push('## Documentation');
    lines.push('');
    lines.push('For more information, refer to the official documentation:');
    lines.push('');
    
    config.docsLinks.forEach(link => {
      const toolName = getToolNameFromDocsLink(link, config.tools);
      lines.push(`- [${toolName}](${link})`);
    });
    lines.push('');
  }
  
  // Footer
  lines.push('---');
  lines.push('');
  lines.push('Generated by StackFast - Full-Stack JavaScript Tech Stack Builder');
  lines.push('');
  
  return lines.join('\n');
}

/**
 * Get a human-readable description for an environment variable
 */
function getEnvVarDescription(key: string, value: string): string {
  void value;

  if (key.includes('DATABASE_URL')) {
    return 'Your database connection string';
  }
  if (key.includes('API_KEY') || key.includes('SECRET_KEY')) {
    return 'Your API secret key';
  }
  if (key.includes('PUBLISHABLE_KEY') || key.includes('PUBLIC')) {
    return 'Your public API key';
  }
  if (key.includes('WEBHOOK')) {
    return 'Webhook secret for verifying requests';
  }
  if (key.includes('URL')) {
    return 'URL configuration';
  }
  
  return 'Configuration value';
}

/**
 * Extract tool name from documentation link
 */
function getToolNameFromDocsLink(link: string, tools: Tool[]): string {
  // Try to match with tool docs
  const tool = tools.find(t => t.docsUrl === link);
  if (tool) {
    return tool.name;
  }
  
  // Extract from URL
  try {
    const url = new URL(link);
    const hostname = url.hostname.replace('www.', '');
    const parts = hostname.split('.');
    if (parts.length > 0 && parts[0]) {
      const name = parts[0];
      return name.charAt(0).toUpperCase() + name.slice(1);
    }
    return 'Documentation';
  } catch {
    return 'Documentation';
  }
}
