import type { Diagnostic, Tool } from "@stackfast/schemas";

const templateGenerators: Record<string, () => string> = {
  "next-config": () => `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`,
  "tsconfig-nextjs": () => JSON.stringify(
    {
      compilerOptions: {
        target: "es5",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ) + "\n",
  "eslint-nextjs": () => `${JSON.stringify({ extends: "next/core-web-vitals" }, null, 2)}\n`,
  "nextjs-root-layout": () => `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Stackfast App",
  description: "Generated by Stackfast",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
  "nextjs-home-page": () => `export default function Home() {
  return (
    <main style={{ padding: "4rem", fontFamily: "system-ui" }}>
      <h1>Stackfast App</h1>
      <p>Your generated starter is ready.</p>
    </main>
  );
}
`,
  "prisma-schema-postgres": () => `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  createdAt DateTime @default(now())
}
`,
  "prisma-client": () => `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
`,
  "clerk-middleware": () => `import { clerkMiddleware } from "@clerk/nextjs/server";

export default clerkMiddleware();

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
};
`,
  "clerk-signin-page": () => `import { SignIn } from "@clerk/nextjs";

export default function Page() {
  return <SignIn />;
}
`,
  "clerk-signup-page": () => `import { SignUp } from "@clerk/nextjs";

export default function Page() {
  return <SignUp />;
}
`,
  "stripe-client": () => `import Stripe from "stripe";

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2024-06-20",
});
`,
  "stripe-webhook": () => `import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { stripe } from "@/lib/stripe";

export async function POST(request: Request) {
  const body = await request.text();
  const signature = headers().get("stripe-signature");

  if (!signature) {
    return NextResponse.json({ error: "Missing Stripe signature" }, { status: 400 });
  }

  const event = stripe.webhooks.constructEvent(
    body,
    signature,
    process.env.STRIPE_WEBHOOK_SECRET!,
  );

  return NextResponse.json({ received: true, type: event.type });
}
`,
  "drizzle-config-postgres": () => `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./src/db/schema.ts",
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
`,
  "drizzle-schema": () => `import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  name: text("name"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
`,
  "drizzle-client": () => `import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not set");
}

const sql = neon(process.env.DATABASE_URL);
export const db = drizzle(sql);
`,
  "nextauth-route": () => `import NextAuth from "next-auth";
import { authOptions } from "@/src/auth/options";

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
`,
  "nextauth-options": () => `import { PrismaAdapter } from "@auth/prisma-adapter";
import GitHubProvider from "next-auth/providers/github";
import type { NextAuthOptions } from "next-auth";
import { prisma } from "@/lib/prisma";

export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma),
  providers: [
    GitHubProvider({
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),
  ],
  session: { strategy: "database" },
};
`,
  "tailwind-config-nextjs": () => `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`,
  "postcss-config": () => `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
  "tailwind-globals": () => `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: light;
}

body {
  margin: 0;
  font-family: system-ui, sans-serif;
}
`,
  "vercel-json": () => `${JSON.stringify({ framework: "nextjs", buildCommand: "npm run build" }, null, 2)}\n`,
  "railway-json": () => `${JSON.stringify({
    build: { builder: "NIXPACKS" },
    deploy: { startCommand: "npm run start", restartPolicyType: "ON_FAILURE", restartPolicyMaxRetries: 10 },
  }, null, 2)}\n`,
  "resend-client": () => `import { Resend } from "resend";

if (!process.env.RESEND_API_KEY) {
  throw new Error("RESEND_API_KEY is not set");
}

export const resend = new Resend(process.env.RESEND_API_KEY);
`,
  "resend-route": () => `import { NextResponse } from "next/server";
import { resend } from "@/src/email/resend";

export async function POST() {
  const result = await resend.emails.send({
    from: process.env.EMAIL_FROM!,
    to: "user@example.com",
    subject: "Hello from Stackfast",
    text: "Your email integration is ready.",
  });

  return NextResponse.json(result);
}
`,
  "s3-client": () => `import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

export const s3 = new S3Client({ region: process.env.AWS_REGION });

export function createUploadUrl(key: string, contentType: string) {
  const command = new PutObjectCommand({
    Bucket: process.env.S3_BUCKET_NAME!,
    Key: key,
    ContentType: contentType,
  });

  return getSignedUrl(s3, command, { expiresIn: 60 });
}
`,
  "s3-presign-route": () => `import { NextResponse } from "next/server";
import { createUploadUrl } from "@/src/storage/s3";

export async function POST(request: Request) {
  const { key, contentType } = await request.json();
  const url = await createUploadUrl(key, contentType);

  return NextResponse.json({ url });
}
`,
};

export function getTemplateContent(templateId: string): string {
  const generator = templateGenerators[templateId];
  if (!generator) {
    throw new Error(`Template not found: ${templateId}`);
  }
  return generator();
}

export function generatePackageJson(config: {
  name: string;
  version: string;
  engines?: { node?: string; bun?: string };
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  scripts: Record<string, string>;
}): string {
  return `${JSON.stringify(
    {
      name: config.name,
      version: config.version,
      private: true,
      ...(config.engines ? { engines: config.engines } : {}),
      scripts: config.scripts,
      dependencies: config.dependencies,
      devDependencies: config.devDependencies,
    },
    null,
    2,
  )}\n`;
}

export function generateEnvExample(config: { example: Record<string, string>; notes: string[] }): string {
  const lines = [
    "# Environment Variables",
    "# Copy this file to .env.local and fill in your actual values",
    "",
  ];

  if (config.notes.length > 0) {
    lines.push("# Notes:", ...config.notes.map((note) => `# - ${note}`), "");
  }

  for (const [key, value] of Object.entries(config.example)) {
    lines.push(`${key}=${value}`);
  }

  return `${lines.join("\n")}\n`;
}

export function generateReadme(config: {
  title?: string;
  intro?: string;
  tools: Tool[];
  postInstallSteps: string[];
  envVars: Record<string, string>;
  docsLinks: string[];
  diagnostics: Diagnostic[];
  includeCaveats?: boolean;
}): string {
  const lines: string[] = [];
  lines.push(`# ${config.title ?? "Stackfast Application"}`, "", "## Overview", "");
  lines.push(config.intro ?? "A modern full-stack application generated by Stackfast.", "");
  lines.push("## Stack", "", ...config.tools.map((tool) => `- **${tool.name}**: ${tool.description}`), "");
  lines.push("## Setup", "", ...config.postInstallSteps.map((step, index) => `${index + 1}. \`${step}\``), "");

  if (Object.keys(config.envVars).length > 0) {
    lines.push("## Environment", "", "Copy `.env.example` to `.env.local` and fill in the values.", "");
    lines.push(...Object.keys(config.envVars).map((key) => `- \`${key}\``), "");
  }

  const warnings = config.diagnostics.filter((diagnostic) => diagnostic.level === "warning");
  if (config.includeCaveats && warnings.length > 0) {
    lines.push("## Caveats", "", ...warnings.map((warning) => `- ${warning.message}`), "");
  }

  if (config.docsLinks.length > 0) {
    lines.push("## Documentation", "", ...config.docsLinks.map((link) => `- ${link}`), "");
  }

  lines.push("---", "", "Generated by Stackfast.", "");
  return lines.join("\n");
}

export function generateSetupGuide(config: { projectName: string; tools: Tool[]; steps: string[] }): string {
  const lines = [
    `# Setup Guide: ${config.projectName}`,
    "",
    "## Selected Tools",
    "",
    ...config.tools.map((tool) => `- ${tool.name} (${tool.categoryId})`),
    "",
    "## Steps",
    "",
    ...config.steps.map((step, index) => `${index + 1}. ${step}`),
    "",
  ];
  return lines.join("\n");
}

export function generateAdr(config: { tools: Tool[]; score: number }): string {
  return [
    "# ADR 0001: Generated Stack Selection",
    "",
    "## Status",
    "",
    "Accepted",
    "",
    "## Context",
    "",
    "Stackfast generated this starter from the selected tool combination and compatibility rules.",
    "",
    "## Decision",
    "",
    `Use ${config.tools.map((tool) => tool.name).join(", ")} as the initial stack.`,
    "",
    "## Consequences",
    "",
    `Initial compatibility score: ${config.score}. Review diagnostics before production hardening.`,
    "",
  ].join("\n");
}
