import type { Diagnostic, Tool } from "@stackfast/schemas";

const templateGenerators: Record<string, () => string> = {
  "next-config": () => `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`,
  "tsconfig-nextjs": () => JSON.stringify(
    {
      compilerOptions: {
        target: "es5",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ) + "\n",
  "eslint-nextjs": () => `${JSON.stringify({ extends: "next/core-web-vitals" }, null, 2)}\n`,
  "nextjs-root-layout": () => `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Stackfast App",
  description: "Generated by Stackfast",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
  "nextjs-home-page": () => `export default function Home() {
  return (
    <main style={{ padding: "4rem", fontFamily: "system-ui" }}>
      <h1>Stackfast App</h1>
      <p>Your generated starter is ready.</p>
    </main>
  );
}
`,
  "prisma-schema-postgres": () => `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  createdAt DateTime @default(now())
}
`,
  "prisma-client": () => `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
`,
  "clerk-middleware": () => `import { clerkMiddleware } from "@clerk/nextjs/server";

export default clerkMiddleware();

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
};
`,
  "clerk-signin-page": () => `import { SignIn } from "@clerk/nextjs";

export default function Page() {
  return <SignIn />;
}
`,
  "clerk-signup-page": () => `import { SignUp } from "@clerk/nextjs";

export default function Page() {
  return <SignUp />;
}
`,
  "stripe-client": () => `import Stripe from "stripe";

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2024-06-20",
});
`,
  "stripe-webhook": () => `import { headers } from "next/headers";
import { NextResponse } from "next/server";
import { stripe } from "@/lib/stripe";

export async function POST(request: Request) {
  const body = await request.text();
  const signature = headers().get("stripe-signature");

  if (!signature) {
    return NextResponse.json({ error: "Missing Stripe signature" }, { status: 400 });
  }

  const event = stripe.webhooks.constructEvent(
    body,
    signature,
    process.env.STRIPE_WEBHOOK_SECRET!,
  );

  return NextResponse.json({ received: true, type: event.type });
}
`,
};

export function getTemplateContent(templateId: string): string {
  const generator = templateGenerators[templateId];
  if (!generator) {
    throw new Error(`Template not found: ${templateId}`);
  }
  return generator();
}

export function generatePackageJson(config: {
  name: string;
  version: string;
  engines?: { node?: string; bun?: string };
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  scripts: Record<string, string>;
}): string {
  return `${JSON.stringify(
    {
      name: config.name,
      version: config.version,
      private: true,
      ...(config.engines ? { engines: config.engines } : {}),
      scripts: config.scripts,
      dependencies: config.dependencies,
      devDependencies: config.devDependencies,
    },
    null,
    2,
  )}\n`;
}

export function generateEnvExample(config: { example: Record<string, string>; notes: string[] }): string {
  const lines = [
    "# Environment Variables",
    "# Copy this file to .env.local and fill in your actual values",
    "",
  ];

  if (config.notes.length > 0) {
    lines.push("# Notes:", ...config.notes.map((note) => `# - ${note}`), "");
  }

  for (const [key, value] of Object.entries(config.example)) {
    lines.push(`${key}=${value}`);
  }

  return `${lines.join("\n")}\n`;
}

export function generateReadme(config: {
  title?: string;
  intro?: string;
  tools: Tool[];
  postInstallSteps: string[];
  envVars: Record<string, string>;
  docsLinks: string[];
  diagnostics: Diagnostic[];
  includeCaveats?: boolean;
}): string {
  const lines: string[] = [];
  lines.push(`# ${config.title ?? "Stackfast Application"}`, "", "## Overview", "");
  lines.push(config.intro ?? "A modern full-stack application generated by Stackfast.", "");
  lines.push("## Stack", "", ...config.tools.map((tool) => `- **${tool.name}**: ${tool.description}`), "");
  lines.push("## Setup", "", ...config.postInstallSteps.map((step, index) => `${index + 1}. \`${step}\``), "");

  if (Object.keys(config.envVars).length > 0) {
    lines.push("## Environment", "", "Copy `.env.example` to `.env.local` and fill in the values.", "");
    lines.push(...Object.keys(config.envVars).map((key) => `- \`${key}\``), "");
  }

  const warnings = config.diagnostics.filter((diagnostic) => diagnostic.level === "warning");
  if (config.includeCaveats && warnings.length > 0) {
    lines.push("## Caveats", "", ...warnings.map((warning) => `- ${warning.message}`), "");
  }

  if (config.docsLinks.length > 0) {
    lines.push("## Documentation", "", ...config.docsLinks.map((link) => `- ${link}`), "");
  }

  lines.push("---", "", "Generated by Stackfast.", "");
  return lines.join("\n");
}

export function generateSetupGuide(config: { projectName: string; tools: Tool[]; steps: string[] }): string {
  const lines = [
    `# Setup Guide: ${config.projectName}`,
    "",
    "## Selected Tools",
    "",
    ...config.tools.map((tool) => `- ${tool.name} (${tool.categoryId})`),
    "",
    "## Steps",
    "",
    ...config.steps.map((step, index) => `${index + 1}. ${step}`),
    "",
  ];
  return lines.join("\n");
}

export function generateAdr(config: { tools: Tool[]; score: number }): string {
  return [
    "# ADR 0001: Generated Stack Selection",
    "",
    "## Status",
    "",
    "Accepted",
    "",
    "## Context",
    "",
    "Stackfast generated this starter from the selected tool combination and compatibility rules.",
    "",
    "## Decision",
    "",
    `Use ${config.tools.map((tool) => tool.name).join(", ")} as the initial stack.`,
    "",
    "## Consequences",
    "",
    `Initial compatibility score: ${config.score}. Review diagnostics before production hardening.`,
    "",
  ].join("\n");
}
